version: '3.8'
services:
  db_compte:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_compte'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - my-db_compte:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  web:
    build: .
    environment:
      DB_URI: "mysql+pymysql://user:password@db_compte:3307/db_compte"
    ports:
      - 8090:8090
    depends_on:
      db_compte:
        condition: service_healthy
volumes:
  my-db_compte: